version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: byteorder
    versions:
    - 1.3.4
  rebase-strategy: disabled
